version: "3.8"

volumes:
  rabbitmq_data:

services:  

  consumer:
    build:
      context: ./
      dockerfile: consumer.dockerfile
    image: bryan2chong/onlyfence/consumer
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/consumer
      PYTHONUNBUFFERED: 1
    ports:
            - "5001:5001"
  

  creator:
    build:
      context: ./
      dockerfile: creator.dockerfile
    image: bryan2chong/onlyfence/creator
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/creator
      PYTHONUNBUFFERED: 1 
    ports:
            - "5002:5002"
  content:
    build:
      context: ./
      dockerfile: content.dockerfile
    image: bryan2chong/onlyfence/content
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/content
  
      PYTHONUNBUFFERED: 1  
    ports:
            - "5003:5003"
    depends_on:
      - creator
    
  
  notification:
    build:
      context: ./
      dockerfile: notification.dockerfile
    image: bryan2chong/onlyfence/notification
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/notification
     
      PYTHONUNBUFFERED: 1  
    ports:
            - "5000:5000"
  payment:
    build:
      context: ./
      dockerfile: payment.dockerfile
    image: bryan2chong/onlyfence/payment
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/payment
      PYTHONUNBUFFERED: 1  
    depends_on:
      - creator
    ports:
            - "5005:5005"

  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq

  activity_log:
    build:
      context: ./
      dockerfile: activity_log.dockerfile
    image: bryan2chong/onlyfence/activity_log
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/activity
      PYTHONUNBUFFERED: 1  
      restart: on-failure
      rabbit_host: rabbitmq
      rabbit_port: 5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  error:
    build:
      context: ./
      dockerfile: error.dockerfile
    image: bryan2chong/onlyfence/error
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/error
      PYTHONUNBUFFERED: 1 
      rabbit_host: rabbitmq
      rabbit_port: 5672
    depends_on:
      - rabbitmq
    links:
      - rabbitmq

  subscription_link:
    build:
      context: ./
      dockerfile: subscription_link.dockerfile
    image: bryan2chong/onlyfence/subscription_link
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/subscription_link
      PYTHONUNBUFFERED: 1  
    ports:
            - "5006:5006"

  post_content:
    build:
      context: ./
      dockerfile: post_content.dockerfile
    image: bryan2chong/onlyfence/post_content
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/post_content
      PYTHONUNBUFFERED: 1 
      rabbit_host: rabbitmq
      rabbit_port: 5672
      upload_url: "http://content:5003/upload" 
      subscription_url: "http://subscription_link:5006/subscription/getsubscribers"
      notification_url: "http://notification:5000/notify/"
      creator_url: "http://creator:5002/creator/getinfo/"
    ports:
            - "5102:5102"
    depends_on:
      - content
      - notification
      - subscription_link
      - creator

  view_content:
    build:
      context: ./
      dockerfile: view_content.dockerfile
    image: bryan2chong/onlyfence/view_content
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/view_content
      PYTHONUNBUFFERED: 1 
      rabbit_host: rabbitmq
      rabbit_port: 5672
      creator_URL: "http://creator:5002/creator/price" 
      subscription_url: "http://subscription_link:5006/subscription/status"
      unsubbed_url: "http://content:5003/unsubbed"
      subbed_url: "http://content:5003/subbed"
    ports:
            - "5100:5100"
    depends_on:
        - content
        - subscription_link
        - creator
  subscribe:
    build:
      context: ./
      dockerfile: subscribe.dockerfile
    image: bryan2chong/onlyfence/subscribe
    restart: always
    environment:
      PYTHONUNBUFFERED: 1 
      rabbit_host: rabbitmq
      rabbit_port: 5672
      creator_URL: "http://creator:5002/creator/price" 
      add_subscription_URL: "http://subscription_link:5006/subscription/add"
      add_paymentLog_URL: "http://payment:5005/payments/log"
    ports:
            - "5101:5101"
    depends_on:
        - payment
        - subscription_link
        - creator
